### Tensor Slicing

In [2]:
import numpy as np
import torch

In [3]:
vector = torch.tensor([10, 20, 30, 40, 50, 60])
vector

tensor([10, 20, 30, 40, 50, 60])

In [13]:
# start =2 , stop= 5 (excluded)
print(f"vector[2:5] = {vector[2:5]}")

# start= 2, stop = 4(excluded)
print(f"vector[2:4] = {vector[2:4]}")

# start = 0, stop = 4 (excluded)
print(f"vector[:4] = {vector[:4]}")

# start = 3, stop = 6 (excluded)
print(f"vector[3:] = {vector[3:]}")

# get all the values
print(f"vector[0:6] = {vector[0:6]}")

# get all the values
print(f"vector[0:] = {vector[0:]}")

# get all the values
print(f"vector[:6] = {vector[:6]}")

# get all the values
print(f"vector[:] = {vector[:]}")

vector[2:5] = tensor([30, 40, 50])
vector[2:4] = tensor([30, 40])
vector[:4] = tensor([10, 20, 30, 40])
vector[3:] = tensor([40, 50, 60])
vector[0:6] = tensor([10, 20, 30, 40, 50, 60])
vector[0:] = tensor([10, 20, 30, 40, 50, 60])
vector[:6] = tensor([10, 20, 30, 40, 50, 60])
vector[:] = tensor([10, 20, 30, 40, 50, 60])


In [ ]:
# get alternate values
print(f"vector[::2] = {vector[::2]}")

# get 3rd values
print(f"vector[::3] = {vector[::3]}")

# get all values in reverse order
# print(f"vector[::-1] = {vector[::-1]}")

### create rank2 tensor

In [19]:
matrix = torch.tensor([[10, 20], [30, 40], [50, 60]])
matrix

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [24]:
# get all rows and columns
# matrix[:]
matrix[:, :]

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [ ]:
# get first column
matrix[:, 0]

tensor([10, 30, 50])

In [26]:
# get second column
matrix[:,1]

tensor([20, 40, 60])