## Tensor Creation

In [2]:
import numpy as np 
import torch

Using python data

In [6]:
# using python list
# scalar = torch.tensor(10)
vector = torch.tensor([10, 20, 30, 40])
matrix = torch.tensor([[10, 20], [30, 40]])
matrix

tensor([[10, 20],
        [30, 40]])

In [7]:
# using python tuple
vector_using_tuple = torch.tensor((10, 20, 30, 40))
vector_using_tuple

tensor([10, 20, 30, 40])

### using numpy array

In [9]:
array1 = np.array([10, 20, 30, 40])
vector_using_np_array = torch.tensor(array1)
vector_using_np_array

tensor([10, 20, 30, 40])

In [10]:
matrix_using_np_array =np.array([[10, 20], [30, 40]])
matrix_using_np_array

array([[10, 20],
       [30, 40]])

### Using specific data types

In [11]:
scalar = torch.tensor(10, dtype=torch.float32)
scalar

tensor(10.)

In [12]:
vector = torch.tensor([10, 20, 30, 40], dtype=torch.float32)
vector

tensor([10., 20., 30., 40.])

In [13]:
matrix = torch.tensor([[10, 20], [30, 40]])
matrix

tensor([[10, 20],
        [30, 40]])