## tensor creation using factory methods


In [2]:
import numpy as np
import torch

### empty tensors

In [3]:
empty_tensor = torch.empty(2, 2)
empty_tensor

tensor([[0., 0.],
        [0., 0.]])

### empty tensor copy

In [4]:
empty_tensor_copy = torch.empty_like(empty_tensor)
empty_tensor_copy

tensor([[0., 0.],
        [0., 0.]])

### zero tensor

In [5]:
zeroed_tensor = torch.zeros(3, 3)
zeroed_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Ones

In [6]:
ones_tensor = torch.ones(2, 3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Full tensor

In [7]:
full_tensor = torch.full((3, 3), 57)
full_tensor

tensor([[57, 57, 57],
        [57, 57, 57],
        [57, 57, 57]])

### Using arange

In [8]:
sample_tensor = torch.arange(0, 10)
sample_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Identity Tensor

In [11]:
identity_tensor = torch.eye(5)
identity_tensor


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### diagonal tensor

In [14]:
diagonal_tensor = torch.diag(torch.tensor([0, 1, 2, 3, 4, 5]))
diagonal_tensor

tensor([[0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 2, 0, 0, 0],
        [0, 0, 0, 3, 0, 0],
        [0, 0, 0, 0, 4, 0],
        [0, 0, 0, 0, 0, 5]])

### Using random integers

In [19]:
random_int_tensor = torch.randint(11, 13, (4, 4))
random_int_tensor

tensor([[11, 12, 12, 12],
        [11, 12, 11, 11],
        [11, 11, 12, 12],
        [12, 12, 11, 11]])

### Using random permutation

In [16]:
per_tensor = torch.randperm(10)
per_tensor

tensor([4, 5, 0, 9, 3, 8, 2, 1, 7, 6])